### ISSUE TITLE
"Error: Cannot get screenshot (screenshot selector is probably wrong)"

### ISSUE THREAD

**Issue by RoneoOrg** [apify/actor-content-checker#15]
Hi there,

I've been able to use this promising actor on Apify, **but checking another URL throws me this error**:

```
2021-05-17T05:04:37.952Z INFO  Saving screenshot...
2021-05-17T05:04:37.956Z ERROR The function passed to Apify.main() threw an exception:
2021-05-17T05:04:37.957Z   Error: Cannot get screenshot (screenshot selector is probably wrong)
2021-05-17T05:04:37.957Z       at /home/myuser/src/main.js:63:15
2021-05-17T05:04:37.958Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## What works:

(taken from the documentation)

```
    {
      "url": "https://www.apify.com/change-log",
      "contentSelector": "[class^=change-log__MonthBox-]",
      "sendNotificationTo": "xxxxx@xxxxx.net",
      "proxy": {
        "useApifyProxy": false
      },
      "navigationTimeout": 30000
    }
```

## Not working

```
     {
        "url": "https://www.leboncoin.fr/recherche?text=Neuf",
        "contentSelector": "[class^=styles_Listing_]",
        "sendNotificationTo": "xxxxx@xxxxx.net",
        "proxy": {
          "useApifyProxy": false
        },
        "navigationTimeout": 30000
      }
```

I've double-checked and the selector exists on the page, at least when I visit the website with my own browser.  
The website Leboncoin ships some Bot blockers from Datadome, maybe is the scraping bot from Apify blocked?

Note that also tried with `"useApifyProxy": true` - the same error occurs..

Any hint?

**Comment by metalwarrior665** [comment]
Hello,

Sorry for late reply. You are almost certainly blocked. As you mentioned Leboncoin has strong protections. I recommend using residential proxies (Apify can give free trial).

I'm now adding feature to retry blocked pages.
