### ISSUE TITLE
Ignore Timestamp modifications

### ISSUE THREAD

**Issue by iaeiou** [apify/actor-content-checker#23]
Hi there,

Content Checker works great, thanks!

but I receive many false positives because of the timestamp being updated, triggering a notification.
To be clear, I get emails because the post date changed from "Posted **1** hour ago" to "Posted **2** hour**s** ago"

Is there a way to ignore such modifications?

**Comment by metalwarrior665** [comment]
You will need to just set up a more targeted selector so it does not include this text
