### ISSUE TITLE
Default container starting without puppeteer (instant crash)

### ISSUE THREAD

**Issue by roman-ruzica** [apify/actor-content-checker#6]
Hi, I tried your content checker and it didn't work in the basic "try it" version. I am new to apify, so I understand there maybe a problem with the way the Docker is started, but I couldn't figure out how to fix it on my own. I have added the failed run url along with the log: [https://my.apify.com/view/runs/pcRvjQdbiwYJrse1S](https://my.apify.com/view/runs/pcRvjQdbiwYJrse1S)

**Comment by metalwarrior665** [comment]
Hello,

Thanks for pointing this out, I fixed it. Please try again.

**Comment by roman-ruzica** [comment]
Thanks for the quick fix, works as expected now.

**Comment by roman-ruzica** [comment]
> Hello,
> 
> Thanks for pointing this out, I fixed it. Please try again.

Thanks for the quick fix, works as expected now.
